Add user access function, edit bot message, confirm function, and message manipulation
SERLatBTH/discord pull request #18
Opened 2024-08-21 10:00 UTC by ZuliusRoolf

This pull request includes the following changes:

- Added a user access function in the utility module to check if a user has a specific role or higher.

- Added the ability to edit a bot message.

- Added a confirm function to check if a user has confirmed an action by typing 'yes' or 'no'.

- Added message manipulation functions.

These changes enhance the functionality of the software by providing access control, message editing, and confirmation capabilities.

2024-08-21 10:03 UTC, ZuliusRoolf reviewed
Perhaps a bit over engineered, tell me if I should break the command arguments into smaller functions instead. Maybe even create a class would be good.

For now it works, it has been manually tested so that all features works. Checked somewhat if errors was caught correctly when inserting wrong values.

2024-08-21 13:39 UTC, andreas-bauer commented
I refacatored the `utility.py` file. Have a look at the changes.

2024-08-21 14:08 UTC, andreas-bauer requested changes

2024-08-21 14:08 UTC, andreas-bauer commented on discord-bot/main.py
> +async def message(
This function is too nested and needs to be refactored.

The specific problem is called Nested Conditional and should be replaced with Guard Clauses.

Bad:
```js
someRequest(req, res) {
   const config = someOperation();
   if (!config) {
       res.status(404).send('Config not found')
     } else {
       res.status(200).json(config)
   }
}
```

Better:
```js
someRequest(req, res) {
const config = someOperation();
    if (!config) {
        // exception handling path
        res.status(404).send('Config not found')
        return
    }

    // happy path (the expected result/operation if everything works)
    res.status(200).json(config)
    }
}
```

For this function:
```python
if await user_has_access(interaction, ADMIN_ROLE_ID, minimum=True):
   // do something
```

```python
has_access =  user_has_access(interaction, ADMIN_ROLE_ID, minimum=True)
if not has_access:
   // handle problem

// continue with happy path

```

2024-08-21 14:08 UTC, andreas-bauer commented on discord-bot/main.py
> +        def check(m):
`check()` should be defined outside of the function or as lambda.
Further, the function name `check` is ambiguous and should be replaced with a better name, e.g., `check_user_permission()`.

2024-08-21 14:08 UTC, andreas-bauer commented on discord-bot/main.py
> +        elif action in ['edit', 'delete']:
The handling of both `edit` and `delete` is very nested and hard to understand.

Split up the two actions, even if it introduces some code duplication. 

```python
if action == "send":
   // handle send

if action == "edit":
   // handle edit

if action == "delete":
   // handle delete
```

2024-08-21 14:08 UTC, andreas-bauer commented on discord-bot/main.py
> +        elif action in ['copy', 'move']:
Similar to `edit` and `delete`. Split up the functionality.

2024-08-22 17:09 UTC, ZuliusRoolf reviewed
Decided to move everything to its own class. If there are any heavy commands in the future they can be defined there. Hopefully this is more readable :)

2024-08-22 17:51 UTC, andreas-bauer approved these changes
Looks much better now

2024-08-22 17:51 UTC, merged